spring:
  application:
    name: core-data-business-intelligence
    version: 1.0.0
    description: Core Data Business Intelligence Service
    team:
      name: Firefly Software Solutions Inc
      email: dev@getfirefly.io

firefly:
  service-client:
    enabled: true
    rest:
      max-connections: 200
      response-timeout: 30s
      connect-timeout: 10s
      read-timeout: 30s
      compression-enabled: true
      follow-redirects: true
      max-in-memory-size: 2097152 # 2MB
      default-content-type: application/json
      default-accept-type: application/json
  data:
    enrichment:
      enabled: true
      discovery:
        enabled: true

orbis:
  base-url: https://api.bvdinfo.com
  api-token: ${ORBIS_API_TOKEN}

server:
  port: 8085
